name: Behave Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies on Windows
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add debug steps here
- name: Print Python version
  run: python --version

- name: List installed Python packages
  run: pip list

- name: Print environment variables
  run: env | sort

- name: List test directory contents
  run: dir tests\features

- name: Run Behave tests with detailed logging
  run: |
    behave -f allure_behave.formatter:AllureFormatter -o allure-report tests/features --no-capture -v --logging-level DEBUG > behave.log 2>&1

- name: Output Behave log
  if: always()
  run: cat behave.log

- name: Upload Behave log
  if: always()
  uses: actions/upload-artifact@v3
  with:
    name: behave-log
    path: behave.log
- name: Generate Allure Report (optional)
        if: success() || failure()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact 
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          
      # Upload Behave logs for debugging
      - name: Upload Behave log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: behave-log
          path: behave.log
