name: Behave Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
  
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt || true  # Ignore errors on non-Windows systems
        if [[ "$RUNNER_OS" == "Windows" ]]; then pip install pywin32==306; fi
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromedriver
        
    - name: Install Chrome dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgconf-2-4 \
          libxi6 \
          libxss1 \
          fonts-liberation \
          libappindicator3-1 \
          xdg-utils

    - name: Run Behave tests
      run: |
        source venv/bin/activate
        behave -f allure_behave.formatter:AllureFormatter -o allure-report tests/features/


    - name: Generate Allure Report (optional)
      if: success() || failure()
      run: |
        source venv/bin/activate
        npm install -g allure-commandline --save-dev.
        allure generate allure-results --clean -o allure-report        

    - name: Upload Allure Report as Artifact (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Archive Test Results (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: allure-results
