name: Behave Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: Windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
  
    - name: Install dependencies Linux
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Install Google Chrome
      run: choco install googlechrome --no-progress

    - name: Install ChromeDriver
      run: choco install chromedriver --no-progress
        
    - name: Install Chrome dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgconf-2-4 \
          libxi6 \
          libxss1 \
          fonts-liberation \
          libappindicator3-1 \
          xdg-utils

    - name: Run Behave tests
      run: |
        behave -f allure_behave.formatter:AllureFormatter -o allure-report tests/features/

    - name: Generate Allure Report (optional)
      if: success() || failure()
      run: |
        npm install -g allure-commandline --save-dev.
        allure generate allure-results --clean -o allure-report        

    - name: Upload Allure Report as Artifact (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Archive Test Results (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: allure-results
